# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger:
- main

pool:
  name: test
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

# resources:
#   containers:
#   - container: eshopweb
#     image: phillipyeo/eshopweb:20231109.35

steps:
# - task: NuGetToolInstaller@1

# - task: NuGetCommand@2
#   inputs:
#     restoreSolution: '$(solution)'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:PackageLocation="$(build.artifactStagingDirectory)" /t:restore'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: VSTest@2
  inputs:
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: Docker@2
  displayName: Login to DockerHub
  inputs:
    command: login
    containerRegistry: 'test_docker'

# - task: Docker@2
#   inputs:
#     containerRegistry: 'test_docker'
#     repository: 'phillipyeo/eShopWeb'
#     command: 'buildAndPush'
#     Dockerfile: '**/Dockerfile'
#     buildContext: $(Build.SourcesDirectory)
#     tags: '$(Build.BuildNumber)'

# - script: echo "I can run inside the container (it starts by default)"
#   target:
#     container: eshopweb
# - task: Docker@2
#   displayName: start eshopweb
#   inputs:
#     command: start
#     container: eshopweb

- script: 'docker run -d --name eshopweb phillipyeo/eshopweb:20231109.35 -p 80:80'
  displayName: 'Run Docker'

# - task: Docker@2
#   inputs:
#     containerRegistry: 'test_docker'
#     command: 'start'
#     container: 'eshopweb'
    