# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger:
- main

pool:
  name: test
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

# resources:
#   containers:
#   - container: eshopweb
#     image: phillipyeo/eshopweb:20231109.35

steps:
# - task: NuGetToolInstaller@1

# - task: NuGetCommand@2
#   inputs:
#     restoreSolution: '$(solution)'

# - task: VSBuild@1
#   inputs:
#     solution: '$(solution)'
#     msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:PackageLocation="$(build.artifactStagingDirectory)" /t:restore'
#     platform: '$(buildPlatform)'
#     configuration: '$(buildConfiguration)'

# - task: VSTest@2
#   inputs:
#     platform: '$(buildPlatform)'
#     configuration: '$(buildConfiguration)'

# - task: Docker@2
#   displayName: Login to DockerHub
#   inputs:
#     command: login
#     containerRegistry: 'test_docker'

- task: Docker@2
  displayName: Build and Push to DockerHub
  inputs:
    containerRegistry: 'test_docker'
    repository: 'phillipyeo/sqlserver'
    command: 'build'
    Dockerfile: '$(Build.SourcesDirectory)/src/SqlServer/Dockerfile'
    buildContext: $(Build.SourcesDirectory)
    tags: |
      latest

- task: Docker@2
  displayName: Build and Push to DockerHub
  inputs:
    containerRegistry: 'test_docker'
    repository: 'phillipyeo/publicapi'
    command: 'build'
    Dockerfile: '$(Build.SourcesDirectory)/src/PublicApi/Dockerfile'
    buildContext: $(Build.SourcesDirectory)
    tags: |
      latest

- task: Docker@2
  displayName: Build and Push to DockerHub
  inputs:
    containerRegistry: 'test_docker'
    repository: 'phillipyeo/eShopWeb'
    command: 'build'
    Dockerfile: '$(Build.SourcesDirectory)/src/Web/Dockerfile'
    buildContext: $(Build.SourcesDirectory)
    tags: |
      latest

# - script: echo "I can run inside the container (it starts by default)"
#   target:
#     container: eshopweb
# - task: Docker@2
#   displayName: start eshopweb
#   inputs:
#     command: start
#     container: eshopweb

- script: 'docker run --cap-add SYS_PTRACE -p 1433:1433 --name azuresqledge -d phillipyeo/publicapi:latest'
  displayName: 'Test Run Docker'

- script: 'docker run -d --name publicapi phillipyeo/publicapi:latest -p 5200:5200'
  displayName: 'Test Run Docker'

- script: 'docker run -d --name eshopweb phillipyeo/eshopweb:latest -p 5106:5106'
  displayName: 'Test Run Docker'

# - task: Docker@2
#   inputs:
#     containerRegistry: 'test_docker'
#     command: 'start'
#     container: 'eshopweb'
    