# RUN ALL CONTAINERS FROM ROOT (folder with .sln file):
# docker-compose build
# docker-compose up
#
FROM mcr.microsoft.com/azure-sql-edge AS build
ENV SA_PASSWORD @someThingComplicated1234
ENV ACCEPT_EULA Y
